#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1571524296                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Smart Magnifying Glass with text scanning feature and filters to increase readability and regulated flashlight/reading light

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Magnifying Glass                                
your_link                                 :                      
your_city                                 : Ukraine                                
email_address                             : artemsherbachuk@gmail.com
facebook_username                         :                                           
instagram_username                        : artemsherbachuk
twitter_username                          : 
github_username                           : artem-sherbachuk
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Scan Text
    description                           : recognize text on the camera and turn it into a digital version with regulated font size
    fontawesome_icon_name                 : magic
    
  - title                                 : Regulated Flashlight
    description                           : regulate flashlight intensity, from light to extra bright. use reading light
    fontawesome_icon_name                 : mobile

  - title                                 : Magnifier
    description                           : 30X zoom with swipe up/down gestures, live bulge/magnifier edit
    fontawesome_icon_name                 : play-circle

  - title                                 : Live Reading Filters 
    description                           : Use extra reading filters live to increase clearness and quality of view
    fontawesome_icon_name                 : sync

  - title                                 : App Design Change
    description                           : change app design on the fly, select app UI color and app icon that will more like to you
    fontawesome_icon_name                 : adjust
  
  - title                                 : Simple Usability 
    description                           : very easy to use, simple UI
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
